"""added user league scores

Revision ID: 575814ce0873
Revises: ece52a0f03ca
Create Date: 2026-07-10 10:07:44.890567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575814ce0873'
down_revision: Union[str, Sequence[str], None] = 'ece52a0f03ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_league_scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_user_league_scores_score_id'), 'user_league_scores', ['score_id'], unique=False)
    op.drop_column('users', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_league_scores_score_id'), table_name='user_league_scores')
    op.drop_table('user_league_scores')
    # ### end Alembic commands ###
