"""add external_id to games

Revision ID: 82e1508246f5
Revises: a884bd7c3318
Create Date: 2026-07-08 10:22:26.212709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e1508246f5'
down_revision: Union[str, Sequence[str], None] = 'a884bd7c3318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predictions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('predictions', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('predictions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
