"""added user league scores

Revision ID: c0d4599d1e69
Revises: 575814ce0873
Create Date: 2026-07-10 10:08:05.365278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d4599d1e69'
down_revision: Union[str, Sequence[str], None] = '575814ce0873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_league_scores', ['user_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_league_scores', type_='unique')
    # ### end Alembic commands ###
