"""add external_id to games

Revision ID: ece52a0f03ca
Revises: 82e1508246f5
Create Date: 2026-07-08 10:24:43.476987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece52a0f03ca'
down_revision: Union[str, Sequence[str], None] = '82e1508246f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('api_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'games', ['api_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'api_id')
    # ### end Alembic commands ###
